=== john-friedman/secfiler/sec_xml_specs/sec_specs/edgarlink-online-xml-tech-spec-52/EDGARLink Online XML Schema files/eis_ABS_15GFiler.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 (http://www.altova.com) by knowlinm (KEANE FEDERAL SYSTEMS) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.sec.gov/edgar/abs15gfiler" xmlns:ns1="http://www.sec.gov/edgar/common" targetNamespace="http://www.sec.gov/edgar/abs15gfiler" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.sec.gov/edgar/common" schemaLocation="eis_Common.xsd"/>
	<xs:simpleType name="SUBMISSION_TYPE">
		<xs:annotation>
			<xs:documentation>
            Type of submission you are filing.  Choose a value from the appropriate family of
            Submission Types.  
            </xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="ABS-15G"/>
			<xs:enumeration value="ABS-15G/A"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="FLAG_TYPE">
		<xs:sequence>
			<xs:element name="confirmingCopyFlag" type="ns1:TRUE_FALSE_TYPE" minOccurs="0"/>
			<xs:element name="overrideInternetFlag" type="ns1:TRUE_FALSE_TYPE" minOccurs="0"/>
			<xs:element name="returnCopyFlag" type="ns1:TRUE_FALSE_TYPE" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FILER_TYPE">
		<xs:sequence>
			<xs:element name="filerId" type="ns1:CIK_TYPE"/>
			<xs:element name="filerCcc" type="ns1:CCC_TYPE"/>
			<xs:element name="fileNumber" type="ns1:FILE_NUMBER_TYPE" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="RULE15GA1_ITEM_TYPE">
		<xs:restriction base="xs:token">
			<xs:enumeration value="1.01"/>
			<xs:enumeration value="1.02"/>
			<xs:enumeration value="1.03"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="RULE15GA2_ITEM_TYPE">
		<xs:restriction base="xs:token">
			<xs:enumeration value="2.01"/>
			<xs:enumeration value="2.02"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ISSUER_TYPE">
		<xs:sequence>
			<xs:element name="issuingEntityCik" type="ns1:CIK_TYPE" minOccurs="0"/>
			<xs:element name="issuingEntityName" type="ns1:ENTITY_NAME_TYPE" minOccurs="0"/>
			<xs:element name="issuingEntityHasFileNumber" type="ns1:YES_NO_TYPE" minOccurs="0"/>
			<xs:element name="issuingEntityFileNumber" type="ns1:FILE_NUMBER_TYPE" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SECURITIZER_TYPE">
		<xs:sequence>
			<xs:element name="securitizerHasCik" type="ns1:YES_NO_TYPE"/>
			<xs:element name="securitizerCik" type="ns1:CIK_TYPE" minOccurs="0"/>
			<xs:element name="securitizerHas025FileNumber" type="ns1:YES_NO_TYPE" minOccurs="0"/>
			<xs:element name="securitizerFileNumber" type="ns1:FILE_NUMBER_TYPE" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RULE15GA1_TYPE">
		<xs:sequence>
			<xs:element name="isRule15Ga1" type="ns1:TRUE_FALSE_TYPE" />
			<xs:element name="rule15Ga1Item" type="RULE15GA1_ITEM_TYPE" />
			<xs:element name="filedItem101" type="ns1:YES_NO_TYPE" minOccurs="0"/>
			<xs:element name="fileNumberItem101" type="ns1:FILE_NUMBER_TYPE" minOccurs="0"/>
			<xs:element name="noActivityInitial" type="ns1:YES_NO_TYPE" minOccurs="0"/>
			<xs:element name="noActivityQtr" type="ns1:YES_NO_TYPE" minOccurs="0"/>
			<xs:element name="noActivityAnnual" type="ns1:YES_NO_TYPE" minOccurs="0"/>			
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RULE15GA2_TYPE">
		<xs:sequence>
			<xs:element name="isRule15Ga2" type="ns1:TRUE_FALSE_TYPE"/>
			<xs:element name="rule15Ga2Item" type="RULE15GA2_ITEM_TYPE"/>
		    <xs:element name="isRegistered" type="ns1:YES_NO_TYPE"/>
			<xs:element name="securitizer" type="SECURITIZER_TYPE"/>
			<xs:element name="depositor" type="ns1:DEPOSITOR_TYPE"/>
			<xs:element name="issuer" type="ISSUER_TYPE"/>
			<xs:element name="underwriterCik" type="ns1:CIK_TYPE" minOccurs="0"/>			
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RULE15GA_TYPE">
		<xs:choice>
			<xs:element name="rule15Ga1Type" type="RULE15GA1_TYPE"/>
			<xs:element name="rule15Ga2Type" type="RULE15GA2_TYPE"/>
		</xs:choice>
	</xs:complexType>
	<xs:simpleType name="ASSET_CLASS_TYPE">
		<xs:restriction base="xs:token">
			<xs:enumeration value="Residential mortgages - Prime"/>
			<xs:enumeration value="Residential mortgages - Non-Prime"/>
			<xs:enumeration value="Residential mortgages - HELOC"/>
			<xs:enumeration value="Residential mortgages - Reverse Mortgages"/>
			<xs:enumeration value="Residential mortgages - Manufactured Housing"/>
			<xs:enumeration value="Residential mortgages - Other/Combined"/>
			<xs:enumeration value="Commercial mortgages"/>
			<xs:enumeration value="Auto loans"/>
			<xs:enumeration value="Auto leases"/>
			<xs:enumeration value="Equipment loans"/>
			<xs:enumeration value="Equipment leases"/>
			<xs:enumeration value="Student loans"/>
			<xs:enumeration value="Floorplan financings"/>
			<xs:enumeration value="Debt Securities"/>
			<xs:enumeration value="Resecuritization"/>
			<xs:enumeration value="Credit card"/>
			<xs:enumeration value="Other"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ACCESSION_NUMBER_TYPE">
		<xs:restriction base="xs:string">
			<xs:pattern value="[*]{0}|[0-9]{1,10}\-[0-9]{1,2}\-[0-9]{1,6}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="edgarSubmission">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="schemaVersion" type="ns1:SCHEMA_VERSION_TYPE" minOccurs="0"/>
				<xs:element name="liveTestFlag" type="ns1:LIVE_TEST_TYPE"/>
				<xs:element name="flag" type="FLAG_TYPE" minOccurs="0"/>
				<xs:element name="contact" type="ns1:CONTACT_TYPE" minOccurs="0"/>
				<xs:element name="sros" type="ns1:SROS_TYPE"/>
				<xs:element name="startPeriodOfReport" type="ns1:DATE_TYPE" minOccurs="0"/>
				<xs:element name="periodOfReport" type="ns1:DATE_TYPE" minOccurs="0"/>
				<xs:element name="submissionType" type="SUBMISSION_TYPE"/>
				<xs:element name="accessionNumber" type="ACCESSION_NUMBER_TYPE" minOccurs="0"/>
				<xs:element name="assetClassType" type="ASSET_CLASS_TYPE"/>
				<xs:element name="filer" type="FILER_TYPE"/>
				<xs:element name="rule15GaType" type="RULE15GA_TYPE"/>
				<xs:element name="notifications" type="ns1:NOTIFICATION_TYPE" minOccurs="0"/>
				<xs:element name="moduleSegments" type="ns1:MODULES_SEGMENT_TYPE" minOccurs="0"/>
				<xs:element name="documents" type="ns1:EDGAR_DOCUMENTS_TYPE"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== john-friedman/secfiler/sec_xml_specs/sec_specs/edgarlink-online-xml-tech-spec-52/EDGARLink Online Sample files/Sample_ABS-15G.xml
<?xml version="1.0" encoding="UTF-8"?>
<n1:edgarSubmission xmlns="http://www.sec.gov/edgar/common" xmlns:n1="http://www.sec.gov/edgar/abs15gfiler" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sec.gov/edgar/abs15gfiler eis_ABS_15GFiler.xsd">
<!-- DISCLAIMER:  This is a sample XML submission document for demonstration purposes only and should not be copied verbatim as part of a submission.  Please refer to the EDGARLink Online XML Technical Specification and the related EDGARLink Online Schemas for complete filer-constructed submission information.-->
<!-- Please be aware that these schema locations are for informational purposes only and should not be considered as required items in the EDGARLink Online Schema. -->
<!-- If a reference to a style sheet is included the submission will be suspended by EDGAR.  Please do not include any references to style sheets.-->
	<n1:liveTestFlag>LIVE</n1:liveTestFlag>
	<n1:flag>
		<n1:confirmingCopyFlag>false</n1:confirmingCopyFlag>
		<n1:overrideInternetFlag>false</n1:overrideInternetFlag>
		<n1:returnCopyFlag>false</n1:returnCopyFlag>
	</n1:flag>
	<n1:sros>
		<sroId>NONE</sroId>
	</n1:sros>
	<n1:periodOfReport>04-25-2018</n1:periodOfReport>
	<n1:submissionType>ABS-15G</n1:submissionType>
	<n1:assetClassType>Residential mortgages - Prime</n1:assetClassType>
	<n1:filer>
		<n1:filerId>0000350001</n1:filerId>
		<n1:filerCcc>dazzle#1</n1:filerCcc>
	</n1:filer>
	<n1:rule15GaType>
		<n1:rule15Ga2Type>
			<n1:isRule15Ga2>true</n1:isRule15Ga2>
			<n1:rule15Ga2Item>2.01</n1:rule15Ga2Item>
			<n1:isRegistered>Y</n1:isRegistered>
			<n1:securitizer>
				<n1:securitizerHasCik>Y</n1:securitizerHasCik>
				<n1:securitizerCik>0000350001</n1:securitizerCik>
				<n1:securitizerHas025FileNumber>Y</n1:securitizerHas025FileNumber>
				<n1:securitizerFileNumber>025-00008</n1:securitizerFileNumber>
			</n1:securitizer>
			<n1:depositor>
				<depositorId>0000350001</depositorId>
				<depositorFileNumber>025-00008</depositorFileNumber>
			</n1:depositor>
			<n1:issuer>
				<n1:issuingEntityCik>0000350001</n1:issuingEntityCik>
				<n1:issuingEntityHasFileNumber>Y</n1:issuingEntityHasFileNumber>
				<n1:issuingEntityFileNumber>333-101735</n1:issuingEntityFileNumber>
			</n1:issuer>
		</n1:rule15Ga2Type>
	</n1:rule15GaType>
	<n1:documents>
		<document>
		      <conformedName>test.txt</conformedName>
		      <conformedDocumentType>ABS-15G</conformedDocumentType>
		      <contents>VGhpcyBpcyBhIHRlc3Qgc3VibWlzc2lvbi4=</contents>
		</document>
	</n1:documents>
</n1:edgarSubmission>
